apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: csi-nfs-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts'
    targetRevision: 4.13.1
    chart: csi-driver-nfs
    helm:
      valuesObject:
        image:
          csiProvisioner:
            repository: 'registry.k8s.io/sig-storage/csi-provisioner'
            tag: 'v6.1.1@sha256:d992c36d4ddd6dfa37c81b487e5a673920e1360e2977eb779051df8da1c5787d'
          csiResizer:
            repository: 'registry.k8s.io/sig-storage/csi-resizer'
            tag: 'v2.0.0@sha256:4a95d94e57ad82f6977cd8d4fdcfcfc0b83f02d990e4e7715b688c20970a906d'
          csiSnapshotter:
            repository: 'registry.k8s.io/sig-storage/csi-snapshotter'
            tag: 'v8.4.0@sha256:c7e0a3718832b6197ce8b29fefb3fed3d84f4fbcdf08f4606140dbec2566501d'
          externalSnapshotter:
            repository: 'registry.k8s.io/sig-storage/snapshot-controller'
            tag: 'v8.4.0@sha256:b845f4bbc34d70bd84e92f8021f47704df1de3dbabbd8289969651360b39d605'
          livenessProbe:
            repository: 'registry.k8s.io/sig-storage/livenessprobe'
            tag: 'v2.17.0@sha256:9b75b9ade162136291d5e8f13a1dfc3dec71ee61419b1bfc112e0796ff8a6aa9'
          nfs:
            repository: 'registry.k8s.io/sig-storage/nfsplugin'
            tag: 'v4.13.1@sha256:c1ab25922c8ec4d7f1744c272f28a89898bd020152e3942592c022410b544948'
          nodeDriverRegistrar:
            repository: 'registry.k8s.io/sig-storage/csi-node-driver-registrar'
            tag: 'v2.15.0@sha256:11f199f6bec47403b03cb49c79a41f445884b213b382582a60710b8c6fdc316a'
      parameters:
        - name: 'controller.name'
          value: 'csi-nfs-controller'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-nfs
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: truenas-nfs-soft
  namespace: 'csi-nfs'
provisioner: nfs.csi.k8s.io
parameters:
  server: 'app03l.dev.renklus.ch'
  share: '/mnt/hdd-pool/general/k8s'
  subdir: '${pvc.metadata.namespace}--${pvc.metadata.name}'
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: 'Delete'
volumeBindingMode: 'Immediate'
allowVolumeExpansion: true
mountOptions:
  - soft # soft means the consuming application will receive an error if the NFS server is not reachable
  - noatime
  - nfsvers=4.2
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: truenas-nfs-hard
  namespace: 'csi-nfs'
provisioner: nfs.csi.k8s.io
parameters:
  server: 'app03l.dev.renklus.ch'
  share: '/mnt/hdd-pool/general/k8s'
  subdir: '${pvc.metadata.namespace}--${pvc.metadata.name}'
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: 'Delete'
volumeBindingMode: 'Immediate'
allowVolumeExpansion: true
mountOptions:
  - hard # hard means the consuming application will be interrupted until the NFS server is back online
  - noatime
  - nfsvers=4.2