apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: csi-nfs-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts'
    targetRevision: 4.12.1
    chart: csi-driver-nfs
    helm:
      valuesObject:
        image:
          csiProvisioner:
            repository: 'registry.k8s.io/sig-storage/csi-provisioner'
            tag: 'v5.2.0@sha256:d5e46da8aff7d73d6f00c761dae94472bcda6e78f4f17b3802dc89d44de0111b'
          csiResizer:
            repository: 'registry.k8s.io/sig-storage/csi-resizer'
            tag: 'v1.13.1@sha256:2a0b297cc7c4cd376ac7413df339ff2fdaa1ec9d099aed92b5ea1f031ef7f639'
          csiSnapshotter:
            repository: 'registry.k8s.io/sig-storage/csi-snapshotter'
            tag: 'v8.2.0@sha256:dd788d79cf4c1b8edee6d9b80b8a1ebfc51a38a365c5be656986b129be9ac784'
          externalSnapshotter:
            repository: 'registry.k8s.io/sig-storage/snapshot-controller'
            tag: 'v8.2.0@sha256:9dade8f2f3ab29e3919c41b343f8d77b12178ac51f25574d7ed2d45a3e3ef69d'
          livenessProbe:
            repository: 'registry.k8s.io/sig-storage/livenessprobe'
            tag: 'v2.15.0@sha256:2c5f9dc4ea5ac5509d93c664ae7982d4ecdec40ca7b0638c24e5b16243b8360f'
          nfs:
            repository: 'registry.k8s.io/sig-storage/nfsplugin'
            tag: 'v4.11.0@sha256:ce5b5ccd5eb099dfa2271f771c2dbcb7b51e0670e03a535834855521a2adc791'
          nodeDriverRegistrar:
            repository: 'registry.k8s.io/sig-storage/csi-node-driver-registrar'
            tag: 'v2.13.0@sha256:d7138bcc3aa5f267403d45ad4292c95397e421ea17a0035888850f424c7de25d'
      parameters:
        - name: 'controller.name'
          value: 'csi-nfs-controller'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-nfs
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: truenas-nfs-soft
  namespace: 'csi-nfs'
provisioner: nfs.csi.k8s.io
parameters:
  server: 'app03l.dev.renklus.ch'
  share: '/mnt/hdd-pool/general/k8s'
  subdir: '${pvc.metadata.namespace}--${pvc.metadata.name}'
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: 'Delete'
volumeBindingMode: 'Immediate'
allowVolumeExpansion: true
mountOptions:
  - soft # soft means the consuming application will receive an error if the NFS server is not reachable
  - noatime
  - nfsvers=4.2
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: truenas-nfs-hard
  namespace: 'csi-nfs'
provisioner: nfs.csi.k8s.io
parameters:
  server: 'app03l.dev.renklus.ch'
  share: '/mnt/hdd-pool/general/k8s'
  subdir: '${pvc.metadata.namespace}--${pvc.metadata.name}'
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: 'Delete'
volumeBindingMode: 'Immediate'
allowVolumeExpansion: true
mountOptions:
  - hard # hard means the consuming application will be interrupted until the NFS server is back online
  - noatime
  - nfsvers=4.2