# Helm chart changelog: https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: 'vault'
    targetRevision: '0.27.0'
    helm:
      valuesObject:
        injector:
          image:
            repository: 'hashicorp/vault-k8s'
            tag: '1.3.1'
        agentImage:
          image:
            repository: 'hashicorp/vault'
            tag: '1.15.2'
        server:
          image:
            repository: 'hashicorp/vault'
            tag: '1.15.2'
        csi:
          image:
            repository: 'hashicorp/vault-csi-provider'
            tag: '1.4.1'
          agent:
            image:
              repository: 'hashicorp/vault'
              tag: '1.15.2'
      parameters:
        - name: 'global.namespace'
          value: 'hashicorp-vault-system'
        - name: 'global.namespace'
          value: 'hashicorp-vault-system'
        # - name: 'server.service.type'
        #   value: 'LoadBalancer'
        - name: 'ui.enabled'
          value: 'true'
        - name: 'ui.serviceType'
          value: 'LoadBalancer'
        - name: 'ui.serviceNodePort'
          value: 'null'
         - name: 'ui.loadBalancerSourceRanges'
           value: '{10.0.0.0/8}'
  destination:
    namespace: 'hashicorp-vault-system'
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: 'apps'
    kind: 'StatefulSet'
    name: 'mongodb'
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'