apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: 'prometheus'
    targetRevision: '28.9.1'
    helm:
      parameters:
        - name: 'server.service.type'
          value: 'LoadBalancer'
        - name: 'server.persistentVolume.storageClass'
          value: 'truenas-nfs-hard'
        - name: 'alertmanager.persistence.storageClass'
          value: 'truenas-nfs-hard'
      valuesObject:
        configmapReload:
          prometheus:
            image:
              repository: 'quay.io/prometheus-operator/prometheus-config-reloader'
              tag: 'v0.89.0'
        server:
          image:
            repository: 'quay.io/prometheus/prometheus'
            # if not set appVersion field from Chart.yaml is used
            tag: ''
  destination:
    namespace: prometheus
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# # https://github.com/prometheus-community/helm-charts/issues/4914
#   ignoreDifferences:
#   - group: apps
#     kind: StatefulSet
#     jqPathExpressions:
#       - .spec.volumeClaimTemplates[0].apiVersion
#       - .spec.volumeClaimTemplates[0].kind
#     # - .spec.volumeClaimTemplates[]?.apiVersion
#     # - .spec.volumeClaimTemplates[]?.kind
# ---
# #https://pete8s.medium.com/installing-prometheus-on-kubernetes-with-argocd-a4e99580543d
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 13.7.2
#     chart: kube-prometheus-stack
# destination:
#   server: https://kubernetes.default.svc
#   namespace: prometheus